### ISSUE TITLE
'hubot-skype' is not in the npm registry.

### ISSUE THREAD

**Issue by davidcelis** [netpro2k/hubot-skype#1]
Is the adapter not available (or ready) for usage yet?

``` bash
hubot % npm install hubot-skype
npm http GET https://registry.npmjs.org/hubot-skype
npm http 404 https://registry.npmjs.org/hubot-skype

npm ERR! 404 'hubot-skype' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.
npm ERR! 
npm ERR! System Darwin 12.0.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "hubot-skype"
npm ERR! cwd /Users/david/Code/DECK_Monitoring/hubot
npm ERR! node -v v0.6.18
npm ERR! npm -v 1.1.22
npm ERR! code E404
npm ERR! message 404 Not Found: hubot-skype
npm ERR! errno {}
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/david/Code/DECK_Monitoring/hubot/npm-debug.log
npm not ok
```

**Comment by scottyrb** [comment]
Same problem.

**Comment by jdp** [comment]
Same problem

**Comment by netpro2k** [comment]
Wanted to wait until this was a bit more robust until submitting to npm. It currently is very messy and has a bunch of non-js dependancies that i am not sure how to handle with npm. If anyone has any suggestions would be glad to hear them.

**Comment by benwilber** [comment]
same problem

**Comment by jdp** [comment]
This is messed up, still doesn't work

**Comment by willwh** [comment]
I think you guys need to put in a tiny little bit of effort. "Same problem" - pitiful.

https://github.com/netpro2k/hubot-skype/issues/3 <- I've got it running as per this, on a ubuntu system. As per netpro2k - it doesn't look like he's going to touch this any further so, fork & get going on pull reqs!!

**Comment by emaaaa** [comment]
To install try to add on package.json
"hubot-skype":"git://github.com/netpro2k/hubot-skype.git"

**Comment by kn0ll** [comment]
did u publish yet i'm having same issue??

**Comment by jdp** [comment]
if you don thelp i will unfollow this project!!!!

**Comment by emaaaa** [comment]
@jdp unfollow, but I think you need it, not ?
@catshirt i try to install and @netpro2k say he dosent publish on rubyforge yet. TO install a package in this state use my previous hack

**Comment by davidcelis** [comment]
@jdp: What a ridiculous (and childish) "threat"

**Comment by emaaaa** [comment]
@davidcelis you're right

**Comment by benwilber** [comment]
any word on this?  still having same problem

**Comment by kyteague** [comment]
did fix yet????

plz.

**Comment by netpro2k** [comment]
I have now updated this to work with the latest version of hubot, published to npm, added better error reporting, as well as notes on OS specific issues in the readme.

**Comment by loisaidasam** [comment]
:+1:

**Comment by kn0ll** [comment]
thanks!!
