### ISSUE TITLE
Is it possible to deploy hubot-skype on heroku?

### ISSUE THREAD

**Issue by AlexMikhalev** [netpro2k/hubot-skype#11]
Is it possible to deploy hubot-skype on heroku and what stack do you need to use on heroku?

**Comment by netpro2k** [comment]
hubot-skype depends on having a running skype client on the same machine. I dont believe this is doable on heroku but should be doable on a linux server if you set up a headless skype client.

**Comment by AlexMikhalev** [comment]
thank you.
