### ISSUE TITLE
Debugging possibilities

### ISSUE THREAD

**Issue by peschee** [netpro2k/hubot-skype#17]
Hi

I'm currently trying to setup hubot with the hubot-skype adapter on an Ubuntu 12.x server with a headless skype. So far, it seems that skype is running fine (can connect to it thorugh vnc with x11vnc), I have added the corresponding permissions for Skype4Py and setup all necessary hubot modules.

The hubot instance is running fine with -a skype, however, the bot does not react to any messages sent to him. If I put some debug statements directly in the `skype.coffee` adapter implementation, it seems that messages are intercepted just fine (in the run method). However, the bot does not post any messages in a chat.

Any ideas on how I could debug this further or what the issue might be?

```
npm --version
1.2.14

node --version
v0.10.0

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=12.04
DISTRIB_CODENAME=precise
DISTRIB_DESCRIPTION="Ubuntu 12.04.2 LTS"

/opt/hubot/bin/hubot --version
2.4.8
```

**Comment by Bukashk0zzz** [comment]
The same problem but my OS is OS X 10.8

**Comment by RafaelGorski** [comment]
Have a look to the following repo:
https://github.com/RafaelGorski/VagrantChefHubot

I manage to configure all of it inside a VM.
