### ISSUE TITLE
Installation is very hard

### ISSUE THREAD

**Issue by bsorensen** [netpro2k/hubot-skype#3]
Due to the nature of the documentation, i find it very hard to install properly. So this ticket is mainly for improving the documentation, until it can be improved with a pull request.

My observations so far :
- Hubot has a few built-in adapters, and  adding 'hubot-skype' as a built-in adapter makes it a lot easier to install.
- The headers for skype.coffee has to be modified, so they become identical to the ones for shell and campfire.
- Robot.TextMessage must be replaced with TextMessage.
- When 'hubot' is started using 'bin/hubot -a skype', skype.py _must_ be placed in the folder above the hubot executable.
- Skype4Py must be installed, for this Python 2.x must be used.
- Use x11 as transport in the skype.py program, ie.   s = Skype4Py.Skype(Transport='x11')

**Comment by netpro2k** [comment]
Currently dont have much time to continue development on it. Got this working for our office and figured i would share it as i know many people were looking for this. I would gladly accept any pull requests anyone would like to submit to help improve it.

**Comment by tszming** [comment]
@netpro2k Thanks for your works, this project is really useful! 

(I also agree with @bsorensen that better installation steps is nice to have too)

**Comment by netpro2k** [comment]
I have now updated this to work with the latest version of hubot, published to npm, added better error reporting, as well as notes on OS specific issues in the readme.

Things should now be much easier to set up.
